@appId =1
@flagId = 1
###
# Create flag
POST http://localhost:3000/api/apps/{{appId}}/flags
Content-Type: application/json

{
  "title": "Flag in app 1 number 1",
  "rollout_percentage": 100,
  "circuit_recovery_percentage": 100,
  "error_threshold_percentage": 50

}


###
# Get all flags
GET http://localhost:3000/api/apps/{{appId}}/flags


###
# Get a flag
GET http://localhost:3000/api/flags/{{flagId}}


###
# Remove flag
DELETE http://localhost:3000/api/flags/{{flagId}}


###
# Update flag
PATCH http://localhost:3000/api/flags/{{flagId}}
Content-Type: application/json

{
  "circuit_status": "recovery",
  "is_active": true,
  "is_recoverable": true,
  "circuit_initial_recovery_percentage": 100,
  "circuit_recovery_increment_percentage": 1000,
  "circuit_recovery_percentage": 50,
  "error_threshold_percentage": 700,
  "circuit_recovery_rate": 4000,
  "circuit_recovery_profile": "exponential"
}


###
# close flag
POST http://localhost:3000/api/flags/circuit/{{flagId}}/close

###
# open flag
POST http://localhost:3000/api/flags/circuit/{{flagId}}/open
