@appId =11
@flagId = 10
###
# Create flag
POST http://localhost:3000/api/apps/{{appId}}/flags
Content-Type: application/json

{
  "title": "Flag in app 11 number 3"
}


###
# Get all flags
GET http://localhost:3000/api/apps/{{appId}}/flags


###
# Get a flag
GET http://localhost:3000/api/flags/{{flagId}}


###
# Remove flag
DELETE http://localhost:3000/api/flags/{{flagId}}


###
# Update flag
PATCH http://localhost:3000/api/flags/{{flagId}}
Content-Type: application/json

{
  "error_threshold": 20
}


###
# close flag
POST http://localhost:3000/api/flags/circuit/{{flagId}}/close

###
# open flag
POST http://localhost:3000/api/flags/circuit/{{flagId}}/open
